runners:
  - name: oracle-runner
    cloud: oracle
    instance_type: VM.Standard2.4
    machine_image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaay3v2j3usr4ssfizk4whmooy2hfd4s3l5lkrrcsbkbcdxk5ut6yua
    region: eu-frankfurt-1
    labels:
      - cirun-oracle